---
- hosts: all
  sudo: yes
  tasks: 
    - name: run echo command
      command: echo hello

    - name: install apache webserver on client1
      apt: name=apache2 update_cache=yes state=latest

    - name: set up index.html
      copy: content="<html>
            <header><title>Hello World</title><header>
            <body>Hello World<body></html>" dest=/var/www/html/index.html mode=0644
     

